name: Node Deployement

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
    - name: Install npm dependencies
      run: npm install
      working-directory: ./vue-project
    - uses: stefanoeb/eslint-action@1.0.2
      with:
        working-directory: ./vue-project
        files: src/
    - name: Run build task
      run: npm run build --if-present
      working-directory: ./vue-project
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "vue-project/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"